const document = new Text().ownerDocument;

test(() => {
  const el = document.createElement('div');
  el.setAttribute('id', 'a');
  el.setAttribute('data-x', 'b');
  const map = el.attributes;
  assert_true(map instanceof NamedNodeMap);
  assert_equals(map, el.attributes, 'the same object each time');
  assert_equals(map.length, 2);
  assert_equals(map[0].name, 'id');
  assert_equals(map.item(1).value, 'b');
  assert_equals(map.item(2), null);
  assert_equals(map['data-x'].value, 'b');
  assert_equals(map.getNamedItem('ID').value, 'a');
  assert_equals(map.ID, undefined, 'upper case names are not supported on an HTML element');
  assert_array_equals(Object.keys(map), ['0', '1']);
  assert_array_equals(Object.getOwnPropertyNames(map), ['0', '1', 'id', 'data-x']);
  assert_array_equals([...map].map((a) => a.name), ['id', 'data-x']);
  const added = document.createAttribute('title');
  added.value = 't';
  assert_equals(map.setNamedItem(added), null);
  assert_equals(el.title === undefined ? el.getAttribute('title') : 't', 't');
  assert_equals(map.length, 3);
  const replacement = document.createAttribute('title');
  replacement.value = 'u';
  assert_equals(map.setNamedItem(replacement), added);
  assert_equals(el.getAttribute('title'), 'u');
  assert_equals(map.removeNamedItem('title'), replacement);
  assert_throws_dom('NotFoundError', () => map.removeNamedItem('title'));
  assert_equals(map.length, 2, 'live');
  assert_equals(map.getNamedItemNS(null, 'id').value, 'a');
  assert_equals(map.removeNamedItemNS(null, 'id').value, 'a');
  assert_equals(el.hasAttribute('id'), false);
}, 'NamedNodeMap');

test(() => {
  const el = document.createElement('div');
  const list = el.classList;
  assert_true(list instanceof DOMTokenList);
  assert_equals(list, el.classList);
  assert_equals(list.length, 0);
  assert_equals(el.hasAttribute('class'), false);
  list.add('a', 'b', 'a');
  assert_equals(el.className, 'a b');
  assert_equals(list.length, 2);
  assert_equals(list[1], 'b');
  assert_equals(list.item(5), null);
  assert_true(list.contains('a'));
  assert_false(list.contains('c'));
  assert_equals(list.toggle('c'), true);
  assert_equals(list.toggle('c'), false);
  assert_equals(list.toggle('d', true), true);
  assert_equals(list.toggle('d', true), true);
  assert_equals(list.toggle('e', false), false);
  assert_equals(list.value, 'a b d');
  list.remove('a', 'zzz');
  assert_equals(list.value, 'b d');
  assert_true(list.replace('b', 'x'));
  assert_false(list.replace('nothing', 'y'));
  assert_equals(String(list), 'x d');
  assert_array_equals([...list], ['x', 'd']);
  const seen = [];
  list.forEach((token, index) => seen.push(token + index));
  assert_array_equals(seen, ['x0', 'd1']);
  list.value = '  p   q p ';
  assert_equals(list.length, 2, 'a set: parsed, without duplicates');
  assert_equals(el.className, '  p   q p ', 'until it is updated');
  list.add('r');
  assert_equals(el.className, 'p q r');
  el.className = 'm n';
  assert_equals(list.length, 2, 'live');
  el.classList = 'forwarded';
  assert_equals(el.className, 'forwarded', 'PutForwards');
  list.remove('forwarded');
  assert_equals(el.getAttribute('class'), '', 'emptied, not removed');
  assert_throws_dom('SyntaxError', () => list.add(''));
  assert_throws_dom('InvalidCharacterError', () => list.add('a b'));
  assert_throws_dom('InvalidCharacterError', () => list.toggle('a\tb'));
  assert_throws_js(TypeError, () => list.supports('x'));
  list.value = 'one two';
  list.replace('two', 'one');
  assert_equals(list.value, 'one');
}, 'classList');
