// Usage: EmbedScripts <name> <script.js>... > Scripts.cpp
// Writes the scripts, one after another, as a C++ source that defines `kScript<name>`: an array of string
// pieces that make up the program, cut small enough for every compiler's limit on a string literal.
#include <cstdio>
#include <fstream>
#include <iterator>
#include <sstream>
#include <string>

int main(int argc, char** argv) {
  if (argc < 3) {
    std::fprintf(stderr, "usage: EmbedScripts <name> <script.js>...\n");
    return 2;
  }
  std::string program;
  for (int i = 2; i < argc; ++i) {
    std::ifstream file(argv[i]);
    if (!file) {
      std::fprintf(stderr, "EmbedScripts: cannot open %s\n", argv[i]);
      return 1;
    }
    program.append(std::istreambuf_iterator<char>(file), std::istreambuf_iterator<char>());
    program += "\n";
  }

  const std::string name = argv[1];
  std::printf("// Generated by tools/EmbedScripts.cpp. Do not edit.\n#include \"solar/web/Scripts.h\"\n\nnamespace solar::web {\n\n");
  std::printf("const char* const kScript%s[] = {\n", name.c_str());
  constexpr size_t kPiece = 8000;
  for (size_t start = 0; start < program.size();) {
    size_t end = std::min(program.size(), start + kPiece);
    // Cut at a line end, so that no piece stops in the middle of a character.
    if (end < program.size()) {
      const size_t newline = program.rfind('\n', end);
      if (newline != std::string::npos && newline > start) end = newline + 1;
    }
    std::printf("R\"SOLAR_SCRIPT(%s)SOLAR_SCRIPT\",\n", program.substr(start, end - start).c_str());
    start = end;
  }
  std::printf("nullptr,\n};\n\n}  // namespace solar::web\n");
  return 0;
}
