// Usage: GenEntities <entities.json> > src/html/EntityTables.cpp
// Reads the named character references of the HTML Standard (https://html.spec.whatwg.org/entities.json)
// and writes the table the tokenizer searches: the names, sorted, without the leading "&" and with the
// trailing ";" they have (the legacy ones are in it twice, with and without), and the one or two code
// points each stands for.
#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

namespace {

[[noreturn]] void Die(const std::string& message) {
  std::fprintf(stderr, "GenEntities: %s\n", message.c_str());
  std::exit(1);
}

struct Entry {
  std::string name;
  std::vector<unsigned> points;
};

}  // namespace

int main(int argc, char** argv) {
  if (argc != 2) Die("usage: GenEntities <entities.json>");
  std::ifstream file(argv[1]);
  if (!file) Die(std::string("cannot open ") + argv[1]);
  std::stringstream buffer;
  buffer << file.rdbuf();
  const std::string text = buffer.str();

  std::vector<Entry> entries;
  size_t at = 0;
  while ((at = text.find("\"&", at)) != std::string::npos) {
    const size_t end = text.find('"', at + 2);
    if (end == std::string::npos) Die("unterminated name");
    Entry entry;
    entry.name = text.substr(at + 2, end - at - 2);
    const size_t key = text.find("\"codepoints\"", end);
    const size_t open = text.find('[', key);
    const size_t close = text.find(']', open);
    if (key == std::string::npos || open == std::string::npos || close == std::string::npos) Die("no code points for " + entry.name);
    std::stringstream numbers(text.substr(open + 1, close - open - 1));
    std::string number;
    while (std::getline(numbers, number, ',')) entry.points.push_back(static_cast<unsigned>(std::stoul(number)));
    if (entry.points.empty() || entry.points.size() > 2) Die("unexpected code points for " + entry.name);
    entries.push_back(std::move(entry));
    at = close;
  }
  if (entries.size() < 2000) Die("too few entities: " + std::to_string(entries.size()));
  std::sort(entries.begin(), entries.end(), [](const Entry& a, const Entry& b) { return a.name < b.name; });

  std::printf("// Generated by tools/GenEntities.cpp from the HTML Standard's entities.json: do not edit.\n");
  std::printf("// Regenerate with `make html-tables`.\n");
  std::printf("#include \"solar/html/Entities.h\"\n\nnamespace solar::html {\n\n");
  std::printf("const NamedEntity kNamedEntities[] = {\n");
  for (const Entry& entry : entries) {
    std::printf("    {\"%s\", 0x%X, 0x%X},\n", entry.name.c_str(), entry.points[0], entry.points.size() > 1 ? entry.points[1] : 0);
  }
  std::printf("};\n\nconst size_t kNamedEntityCount = %zu;\n\n}  // namespace solar::html\n", entries.size());
}
