#!/usr/bin/env python3
"""Generates src/css/PropertyData.cpp from W3C's webref (https://github.com/w3c/webref, branch curated, ed/css/*.json).

usage: tools/genprops.py WEBREF_CHECKOUT > src/css/PropertyData.cpp

The table says, for every property the specifications define, its value definition syntax, initial value, whether it
is inherited and, for a shorthand, its longhands; and, for every type the syntaxes refer to, what the type is.
Where several levels of a specification define a name, the highest level wins.
"""
import glob
import json
import os
import re
import sys

root = sys.argv[1]


def level(path):
    m = re.search(r"-(\d+)\.json$", path)
    return int(m.group(1)) if m else 1


def cstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


# Types whose syntax the specifications give only in prose.
SUPPLEMENT = {
    "<alpha-value>": "<number> | <percentage>",
    "<grid-line>": "auto | <custom-ident> | [ <integer> && <custom-ident>? ] | [ span && [ <integer> || <custom-ident> ] ]",
    "<cursor-image>": "<url> [ <number> <number> ]?",
    "<feature-tag-value>": "<string> [ <integer [0,\u221e]> | on | off ]?",
    "<palette-identifier>": "<dashed-ident>",
    "<compat-auto>": "searchfield | textarea | checkbox | radio | menulist | listbox | meter | progress-bar | button",
    "<compat-special>": "textfield | menulist-button",
    "<content-replacement>": "<image>",
    "<timeline-range-name>": "cover | contain | entry | exit | entry-crossing | exit-crossing",
    "<try-tactic>": "flip-block || flip-inline || flip-start",
    "<size-keyword>": "fit-content | max-content | min-content",
}

# Where the machine-readable syntax is not what browsers accept.
OVERRIDE = {
    "<paint>": "none | <color> | <url> [ none | <color> ]? | context-fill | context-stroke",
}

props, types, functions = {}, {}, {}


def add_type(name, syntax, lv):
    old = types.get(name)
    if old is None or lv >= old[0]:
        types[name] = (lv, syntax)


def collect(entry, lv):
    """Types and functions an entry defines, itself and nested."""
    name, syntax = entry.get("name"), entry.get("value")
    if name and syntax is None and entry.get("values"):
        keywords = [x["value"] for x in entry["values"] if x.get("type") == "value" and re.fullmatch(r"[a-zA-Z0-9-]+", x.get("value", ""))]
        if keywords:
            syntax = " | ".join(keywords)
    if name and syntax is not None and entry.get("type") in ("type", "function", None):
        add_type(name, syntax, lv)
        if entry.get("type") == "function":
            functions[name] = (entry.get("href", ""), lv)
    for child in entry.get("values", []):
        if child.get("type") in ("type", "function"):
            collect(child, lv)


for path in sorted(glob.glob(os.path.join(root, "ed/css/*.json"))):
    data = json.load(open(path))
    lv = level(path)
    for p in data.get("properties", []):
        if "value" not in p:
            continue
        old = props.get(p["name"])
        if old is None or lv >= old[0]:
            props[p["name"]] = (lv, p)
        collect({"values": p.get("values", [])}, lv)
    for v in data.get("values", []):
        collect(v, lv)

for name, syntax in OVERRIDE.items():
    types[name] = (99, syntax)

# <foo-function> is the functions the specification names funcdef-foo-*.
for name in list(SUPPLEMENT):
    if name not in types:
        types[name] = (0, SUPPLEMENT[name])
for m in re.finditer(r"<([a-z-]+)-function>", " ".join(p[1]["value"] for p in props.values()) + " ".join(t[1] for t in types.values())):
    group = m.group(1)
    key = "<%s-function>" % group
    if key in types:
        continue
    members = sorted(f for f, (href, _) in functions.items() if ("#funcdef-" + group + "-") in href)
    if members:
        types[key] = (0, " | ".join("<%s>" % f for f in members))

out = ['// Generated by tools/genprops.py from W3C webref (https://github.com/w3c/webref). Do not edit.', '#include "solar/css/Properties.h"', "", "namespace solar::css {", ""]
out.append("const PropertyDefinition kPropertyDefinitions[] = {")
for name in sorted(props):
    p = props[name][1]
    longhands = p.get("longhands", [])
    lh = "{" + ", ".join(cstr(x) for x in longhands) + "}"
    inherited = "true" if p.get("inherited", "no").strip().lower().startswith("yes") else "false"
    resets = "{" + ", ".join(cstr(x) for x in p.get("resetLonghands", [])) + "}"
    out.append(f"    {{{cstr(name)}, {cstr(p['value'])}, {cstr(p.get('initial', '') if isinstance(p.get('initial', ''), str) else '')}, {inherited}, {lh}, {resets}}},")
out.append("};")
out.append("const size_t kPropertyDefinitionCount = sizeof(kPropertyDefinitions) / sizeof(kPropertyDefinitions[0]);")
out.append("")
out.append("const TypeDefinition kTypeDefinitions[] = {")
for name in sorted(types):
    out.append(f"    {{{cstr(name)}, {cstr(types[name][1])}}},")
out.append("};")
out.append("const size_t kTypeDefinitionCount = sizeof(kTypeDefinitions) / sizeof(kTypeDefinitions[0]);")
out.append("")
out.append("}  // namespace solar::css")
print("\n".join(out))
