// Usage: GenPublicSuffix <public_suffix_list.dat> > src/url/PublicSuffixTables.cpp
// Reads the Public Suffix List (https://publicsuffix.org/list/) and writes the table PublicSuffix.cpp
// searches. A rule's labels are converted to what a URL's host would hold, so they can be compared
// with it as they are.
#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <map>
#include <string>

#include "solar/url/Parser.h"
#include "solar/url/Url.h"

namespace {

[[noreturn]] void Die(const std::string& message) {
  std::fprintf(stderr, "GenPublicSuffix: %s\n", message.c_str());
  std::exit(1);
}

// "münchen.de" as a URL's host serializes it: lower case, punycode.
std::string ToHost(const std::string& name) {
  const auto url = solar::url::Parse("https://" + name + "/");
  if (!url || !url->host) Die("not a domain: " + name);
  return *url->host;
}

}  // namespace

int main(int argc, char** argv) {
  if (argc != 2) Die("usage: GenPublicSuffix <public_suffix_list.dat>");
  std::ifstream file(argv[1]);
  if (!file) Die(std::string("cannot open ") + argv[1]);

  std::map<std::string, unsigned> rules;
  std::string version, commit, line;
  while (std::getline(file, line)) {
    if (line.starts_with("// VERSION: ")) version = line.substr(12);
    if (line.starts_with("// COMMIT: ")) commit = line.substr(11);
    if (line.empty() || line.starts_with("//")) continue;
    // A rule ends at the first white space; what follows is a comment.
    line = line.substr(0, line.find_first_of(" \t\r"));
    if (line.empty()) continue;

    unsigned flag = 1;
    if (line.starts_with("!")) {
      flag = 4;
      line.erase(0, 1);
    } else if (line.starts_with("*.")) {
      flag = 2;
      line.erase(0, 2);
    }
    rules[ToHost(line)] |= flag;
  }
  if (rules.empty()) Die("no rules found");

  std::printf("// Generated by tools/GenPublicSuffix.cpp from the Public Suffix List, which is\n");
  std::printf("// distributed under the Mozilla Public License 2.0 (https://mozilla.org/MPL/2.0/).\n");
  std::printf("// List version %s, commit %s. Do not edit.\n", version.c_str(), commit.c_str());
  std::printf("#include \"solar/url/PublicSuffixTables.h\"\n\nnamespace solar::url::psl {\n\nconst Rule kRules[] = {\n");
  size_t column = 0;
  for (const auto& [key, flags] : rules) {
    const std::string entry = "{\"" + key + "\", " + std::to_string(flags) + "},";
    if (column == 0) std::printf("    ");
    std::printf("%s", entry.c_str());
    column += entry.size() + 1;
    if (column > 100) {
      std::printf("\n");
      column = 0;
    } else {
      std::printf(" ");
    }
  }
  if (column != 0) std::printf("\n");
  std::printf("};\n\nconst size_t kRuleCount = %zu;\n\n}  // namespace solar::url::psl\n", rules.size());
  return 0;
}
