#!/usr/bin/env python3
"""Generates src/text/UnicodeTables.cpp from the Unicode Character Database: the properties that text layout needs (line breaking, east asian
width, emoji, grapheme and word breaking, bidi, general category, case mapping).

usage: tools/gentext.py UCD_DIR > src/text/UnicodeTables.cpp   (UCD_DIR holds the files named in FILES, from https://www.unicode.org/Public/<version>/ucd/)
"""
import re
import sys

ucd = sys.argv[1]
VERSION = "18.0.0"


def read(name):
    return open(f"{ucd}/{name}", encoding="utf-8").read().splitlines()


def parse_ranges(name, missing_default=True):
    """-> (default, [(first, last, value)]) with @missing lines applied first."""
    missing = []
    entries = []
    for line in read(name):
        m = re.match(r"#\s*@missing:\s*([0-9A-F]+)\.\.([0-9A-F]+);\s*(?:[^;]*;\s*)?([^#;]+)", line)
        if m:
            missing.append((int(m.group(1), 16), int(m.group(2), 16), m.group(3).strip()))
            continue
        line = line.split("#")[0].strip()
        if not line:
            continue
        parts = [p.strip() for p in line.split(";")]
        rng = parts[0]
        if ".." in rng:
            a, b = rng.split("..")
        else:
            a = b = rng
        entries.append((int(a, 16), int(b, 16), parts[1]))
    return missing, entries


def table(name, default, key=None):
    """A dense lookup applied in file order: later lines win. Returns a sorted list of merged ranges (value != default)."""
    missing, entries = parse_ranges(name)
    cells = {}
    spans = []
    for first, last, value in missing:
        spans.append((first, last, value))
    for first, last, value in entries:
        spans.append((first, last, value))
    # paint into a list of runs
    runs = [(0, 0x10FFFF, default)]
    for first, last, value in spans:
        out = []
        for a, b, v in runs:
            if b < first or a > last:
                out.append((a, b, v))
                continue
            if a < first:
                out.append((a, first - 1, v))
            out.append((max(a, first), min(b, last), value))
            if b > last:
                out.append((last + 1, b, v))
        runs = out
    runs.sort()
    merged = []
    for a, b, v in runs:
        if merged and merged[-1][2] == v and merged[-1][1] + 1 == a:
            merged[-1] = (merged[-1][0], b, v)
        else:
            merged.append((a, b, v))
    return [(a, b, v) for a, b, v in merged if v != default]


def emit_enum(title, values):
    return "// %s: %s\n" % (title, ", ".join("%d %s" % (i, v) for i, v in enumerate(values)))


out = []
out.append("// Generated by tools/gentext.py from the Unicode Character Database %s: do not edit.\n" % VERSION)
out.append('#include "solar/text/Unicode.h"\n\nnamespace solar::text {\n\nnamespace {\n')


def emit_ranges(cname, ranges, values, comment):
    idx = {v: i for i, v in enumerate(values)}
    out.append(emit_enum(comment, values))
    out.append("const Range %s[] = {\n" % cname)
    line = "  "
    for a, b, v in ranges:
        item = "{0x%X,0x%X,%d}," % (a, b, idx[v])
        if len(line) + len(item) > 140:
            out.append(line + "\n")
            line = "  "
        line += item
    out.append(line + "\n};\n\n")


# Line_Break
LB = ["XX", "AI", "AL", "B2", "BA", "BB", "BK", "CB", "CJ", "CL", "CM", "CP", "CR", "EB", "EM", "EX", "GL", "H2", "H3", "HL", "HY", "ID", "IN", "IS", "JL", "JT", "JV", "LF", "NL", "NS", "NU", "OP", "PO", "PR", "QU", "RI", "SA", "SG", "SP", "SY", "WJ", "ZW", "ZWJ", "AK", "AP", "AS", "VF", "VI"]
lb = table("LineBreak.txt", "XX")
for a, b, v in lb:
    if v not in LB:
        LB.append(v)
emit_ranges("kLineBreak", lb, LB, "Line_Break")

# East_Asian_Width
EAW = ["N", "A", "F", "H", "Na", "W"]
emit_ranges("kEastAsianWidth", table("EastAsianWidth.txt", "N"), EAW, "East_Asian_Width")

# Extended_Pictographic
ep = [(a, b, 1) for a, b, v in parse_ranges("emoji-data.txt")[1] if v == "Extended_Pictographic"]
emit_ranges_rows = []
out.append("// Extended_Pictographic\nconst Range kExtendedPictographic[] = {\n  ")
line = ""
for a, b, v in sorted(ep):
    item = "{0x%X,0x%X,1}," % (a, b)
    if len(line) + len(item) > 140:
        out.append(line + "\n  ")
        line = ""
    line += item
out.append(line + "\n};\n\n")

# Grapheme_Cluster_Break
GCB = ["Other", "CR", "LF", "Control", "Extend", "ZWJ", "Regional_Indicator", "Prepend", "SpacingMark", "L", "V", "T", "LV", "LVT"]
emit_ranges("kGraphemeBreak", table("GraphemeBreakProperty.txt", "Other"), GCB, "Grapheme_Cluster_Break")

# Indic_Conjunct_Break (for grapheme clusters, GB9c)
incb = []
for line in read("DerivedCoreProperties.txt"):
    m = re.match(r"([0-9A-F.]+)\s*;\s*InCB\s*;\s*(\w+)", line)
    if m:
        rng = m.group(1)
        a, b = (rng.split("..") + [rng])[:2] if ".." in rng else (rng, rng)
        incb.append((int(a, 16), int(b, 16), m.group(2)))
INCB = ["None", "Linker", "Consonant", "Extend"]
emit_ranges("kIndicConjunctBreak", sorted(incb), INCB, "Indic_Conjunct_Break")

# Word_Break
WB = ["Other", "CR", "LF", "Newline", "Extend", "ZWJ", "Regional_Indicator", "Format", "Katakana", "Hebrew_Letter", "ALetter", "Single_Quote", "Double_Quote", "MidNumLet", "MidLetter", "MidNum", "Numeric", "ExtendNumLet", "WSegSpace"]
emit_ranges("kWordBreak", table("WordBreakProperty.txt", "Other"), WB, "Word_Break")

# Bidi_Class
BIDI = ["L", "R", "AL", "EN", "ES", "ET", "AN", "CS", "NSM", "BN", "B", "S", "WS", "ON", "LRE", "LRO", "RLE", "RLO", "PDF", "LRI", "RLI", "FSI", "PDI"]
bidi_long = {"Left_To_Right": "L", "Right_To_Left": "R", "Arabic_Letter": "AL", "European_Number": "EN", "European_Separator": "ES", "European_Terminator": "ET", "Arabic_Number": "AN",
             "Common_Separator": "CS", "Nonspacing_Mark": "NSM", "Boundary_Neutral": "BN", "Paragraph_Separator": "B", "Segment_Separator": "S", "White_Space": "WS", "Other_Neutral": "ON"}
missing, entries = parse_ranges("DerivedBidiClass.txt")
missing = [(a, b, bidi_long.get(v, v)) for a, b, v in missing]
entries = [(a, b, bidi_long.get(v, v)) for a, b, v in entries]
open("/dev/null", "w")
# paint
runs = [(0, 0x10FFFF, "L")]
for first, last, value in missing + entries:
    o = []
    for a, b, v in runs:
        if b < first or a > last:
            o.append((a, b, v)); continue
        if a < first:
            o.append((a, first - 1, v))
        o.append((max(a, first), min(b, last), value))
        if b > last:
            o.append((last + 1, b, v))
    runs = o
runs.sort()
mg = []
for a, b, v in runs:
    if mg and mg[-1][2] == v and mg[-1][1] + 1 == a:
        mg[-1] = (mg[-1][0], b, v)
    else:
        mg.append((a, b, v))
emit_ranges("kBidiClass", [(a, b, v) for a, b, v in mg if v != "L"], BIDI, "Bidi_Class")

# Bidi paired brackets: code point, pair, type (o/c)
brackets = []
for line in read("BidiBrackets.txt"):
    line = line.split("#")[0].strip()
    if not line:
        continue
    p = [x.strip() for x in line.split(";")]
    brackets.append((int(p[0], 16), int(p[1], 16), p[2]))
out.append("const Bracket kBrackets[] = {\n")
for cp, pair, t in sorted(brackets):
    out.append("  {0x%X,0x%X,%d},\n" % (cp, pair, 1 if t == "o" else 2))
out.append("};\n\n")

# Bidi mirroring
mirror = []
for line in read("BidiMirroring.txt"):
    line = line.split("#")[0].strip()
    if not line:
        continue
    p = [x.strip() for x in line.split(";")]
    mirror.append((int(p[0], 16), int(p[1], 16)))
out.append("const Mapping kMirror[] = {\n")
for cp, m in sorted(mirror):
    out.append("  {0x%X,0x%X},\n" % (cp, m))
out.append("};\n\n")

# General_Category
GC = ["Cn", "Lu", "Ll", "Lt", "Lm", "Lo", "Mn", "Mc", "Me", "Nd", "Nl", "No", "Pc", "Pd", "Ps", "Pe", "Pi", "Pf", "Po", "Sm", "Sc", "Sk", "So", "Zs", "Zl", "Zp", "Cc", "Cf", "Cs", "Co"]
gcm, gce = parse_ranges("DerivedGeneralCategory.txt")
runs = [(0, 0x10FFFF, "Cn")]
for first, last, value in gcm + gce:
    o = []
    for a, b, v in runs:
        if b < first or a > last:
            o.append((a, b, v)); continue
        if a < first:
            o.append((a, first - 1, v))
        o.append((max(a, first), min(b, last), value))
        if b > last:
            o.append((last + 1, b, v))
    runs = o
runs.sort()
mg = []
for a, b, v in runs:
    if mg and mg[-1][2] == v and mg[-1][1] + 1 == a:
        mg[-1] = (mg[-1][0], b, v)
    else:
        mg.append((a, b, v))
emit_ranges("kGeneralCategory", [(a, b, v) for a, b, v in mg if v != "Cn"], GC, "General_Category")

# Simple case mappings from UnicodeData.txt
upper, lower, title = [], [], []
for line in read("UnicodeData.txt"):
    f = line.split(";")
    cp = int(f[0], 16)
    if f[12]:
        upper.append((cp, int(f[12], 16)))
    if f[13]:
        lower.append((cp, int(f[13], 16)))
    if f[14]:
        title.append((cp, int(f[14], 16)))
for name, rows in (("kUpper", upper), ("kLower", lower), ("kTitle", title)):
    out.append("const Mapping %s[] = {\n" % name)
    line = "  "
    for cp, m in rows:
        item = "{0x%X,0x%X}," % (cp, m)
        if len(line) + len(item) > 140:
            out.append(line + "\n")
            line = "  "
        line += item
    out.append(line + "\n};\n\n")

# SpecialCasing, unconditional entries: code point -> lower/title/upper strings
special = []
for line in read("SpecialCasing.txt"):
    line = line.split("#")[0].strip()
    if not line:
        continue
    p = [x.strip() for x in line.split(";")]
    if len(p) > 5 and p[4]:
        continue  # conditional
    cps = lambda s: [int(x, 16) for x in s.split()] if s else []
    special.append((int(p[0], 16), cps(p[1]), cps(p[2]), cps(p[3])))
out.append("const Special kSpecial[] = {\n")
for cp, lo, ti, up in special:
    def arr(v):
        v = (v + [0, 0, 0])[:3]
        return "{%s}" % ",".join("0x%X" % x for x in v)
    out.append("  {0x%X,%s,%s,%s},\n" % (cp, arr(lo), arr(ti), arr(up)))
out.append("};\n\n")

out.append("}  // namespace\n\n")
for cname, kind in (("kLineBreak", "LineBreakTable"), ):
    pass
out.append("""const Table& LineBreakTable() { static const Table t{kLineBreak, sizeof kLineBreak / sizeof *kLineBreak}; return t; }
const Table& EastAsianWidthTable() { static const Table t{kEastAsianWidth, sizeof kEastAsianWidth / sizeof *kEastAsianWidth}; return t; }
const Table& ExtendedPictographicTable() { static const Table t{kExtendedPictographic, sizeof kExtendedPictographic / sizeof *kExtendedPictographic}; return t; }
const Table& GraphemeBreakTable() { static const Table t{kGraphemeBreak, sizeof kGraphemeBreak / sizeof *kGraphemeBreak}; return t; }
const Table& IndicConjunctBreakTable() { static const Table t{kIndicConjunctBreak, sizeof kIndicConjunctBreak / sizeof *kIndicConjunctBreak}; return t; }
const Table& WordBreakTable() { static const Table t{kWordBreak, sizeof kWordBreak / sizeof *kWordBreak}; return t; }
const Table& BidiClassTable() { static const Table t{kBidiClass, sizeof kBidiClass / sizeof *kBidiClass}; return t; }
const Table& GeneralCategoryTable() { static const Table t{kGeneralCategory, sizeof kGeneralCategory / sizeof *kGeneralCategory}; return t; }
const BracketTable& Brackets() { static const BracketTable t{kBrackets, sizeof kBrackets / sizeof *kBrackets}; return t; }
const MappingTable& MirrorMap() { static const MappingTable t{kMirror, sizeof kMirror / sizeof *kMirror}; return t; }
const MappingTable& UpperMap() { static const MappingTable t{kUpper, sizeof kUpper / sizeof *kUpper}; return t; }
const MappingTable& LowerMap() { static const MappingTable t{kLower, sizeof kLower / sizeof *kLower}; return t; }
const MappingTable& TitleMap() { static const MappingTable t{kTitle, sizeof kTitle / sizeof *kTitle}; return t; }
const SpecialTable& SpecialCasing() { static const SpecialTable t{kSpecial, sizeof kSpecial / sizeof *kSpecial}; return t; }

}  // namespace solar::text
""")
sys.stdout.write("".join(out))
